### Aliya Irfani
### 2109106007
### Informatika A 2021

## POSTTEST 7 TENSORFLOW

In [1]:
import tensorflow as tf

In [4]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.0919173 , -0.50867236, -0.60065955, -1.1253885 , -0.8871544 ],
       [-0.6092709 ,  0.587739  , -0.29714295, -0.8393197 ,  0.9166867 ],
       [-0.10452037,  1.3851545 ,  0.4848608 ,  0.2158733 ,  0.8586742 ],
       [ 0.76974714, -0.31655243, -0.17181592, -0.544253  , -1.0112499 ],
       [-1.3278526 ,  0.12330144,  1.8880543 , -1.6810323 ,  1.5303435 ]],
      dtype=float32)>

In [14]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97], shape = [5,5], dtype = tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

### Menampilkan dimensi dari 2 variable

In [17]:
# menampilkan dimensi variable prime_tensor dengan dimension display
dimensi_prime = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97], shape = [5,5])
dimensi_prime.shape

TensorShape([5, 5])

In [16]:
tf.shape(dimensi_prime)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

In [18]:
# menampilkan dimensi variabele random_tensor dengan dimension expansion
dimensi_random = tf.random.normal([5,5], seed=1)
dimensi_random.shape

TensorShape([5, 5])

In [19]:
tf.expand_dims(dimensi_random, axis=0).shape

TensorShape([1, 5, 5])

###  Perhitungan aritmetika 2 variable

In [21]:
# pertambahan
a = random_tensor
b = prime_tensor
tf.add(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.9080827,  2.4913278,  4.3993406,  5.8746114, 10.112845 ],
       [12.390729 , 17.587738 , 18.702858 , 22.16068  , 29.916687 ],
       [30.89548  , 38.385155 , 41.48486  , 43.215874 , 47.858673 ],
       [53.76975  , 58.68345  , 60.828182 , 66.45575  , 69.98875  ],
       [71.67215  , 79.1233   , 84.888054 , 87.31897  , 98.53034  ]],
      dtype=float32)>

In [27]:
# pengurangan
tf.subtract(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -3.0919173,  -3.5086722,  -5.6006594,  -8.125388 , -11.887155 ],
       [-13.609271 , -16.412262 , -19.297142 , -23.83932  , -28.083313 ],
       [-31.10452  , -35.614845 , -40.51514  , -42.784126 , -46.141327 ],
       [-52.23025  , -59.31655  , -61.171818 , -67.54425  , -72.01125  ],
       [-74.32785  , -78.8767   , -81.111946 , -90.68103  , -95.46966  ]],
      dtype=float32)>

In [28]:
# perkalian
tf.matmul(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-151.82489 , -170.6307  , -182.03392 , -199.52902 , -220.95015 ],
       [  19.64482 ,   20.067848,   20.824324,   21.826649,   25.703646],
       [ 106.953156,  121.745705,  130.11285 ,  142.86145 ,  160.42662 ],
       [-110.568634, -121.42901 , -126.34338 , -135.74675 , -145.52136 ],
       [  80.09727 ,   89.68681 ,   97.58923 ,   98.29871 ,  106.79794 ]],
      dtype=float32)>

In [29]:
# pembagian
tf.divide(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.54595864, -0.16955745, -0.12013191, -0.16076979, -0.0806504 ],
       [-0.04686699,  0.03457288, -0.0156391 , -0.03649216,  0.03160989],
       [-0.00337162,  0.03743661,  0.01182587,  0.00502031,  0.01826966],
       [ 0.01452353, -0.0053653 , -0.00281665, -0.00812318, -0.01424296],
       [-0.01818976,  0.00156078,  0.02274764, -0.018888  ,  0.01577674]],
      dtype=float32)>

In [30]:
# pangkat
tf.pow(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.19228339e+00, -1.31617740e-01, -7.81883299e-02,
        -2.28621626e+00, -2.67911464e-01],
       [-1.59417279e-03,  1.19161661e-04, -9.69043457e-11,
        -1.77963376e-02,  8.02429989e-02],
       [-3.93757223e-31,  1.71962547e+05,  1.28914064e-13,
         2.34722170e-29,  7.76132976e-04],
       [ 9.47214630e-07, -3.35964561e-30, -0.00000000e+00,
        -1.98909392e-18, -2.21285462e+00],
       [-9.77103424e+08,  0.00000000e+00,  8.11336353e+22,
        -1.19198056e+20,  8.40478164e+17]], dtype=float32)>

###  Nilai maksimum dan minimum dari variable random_tensor

In [34]:
argmax = random_tensor
max1 = tf.argmax(argmax, axis=0) # unuk malihat lokasi nilai max per kolom
max1

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 2, 4, 2, 4], dtype=int64)>

In [35]:
max2 = tf.argmax(argmax, axis=1) # unuk malihat lokasi nilai max per baris
max2

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 4, 1, 0, 2], dtype=int64)>

In [38]:
argmin = random_tensor
min1 = tf.argmin(argmin, axis = 0) # unuk malihat lokasi nilai min per kolom
min1

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 0, 0, 4, 3], dtype=int64)>

In [39]:
min2 = tf.argmin(argmin, axis=1) # unuk malihat lokasi nilai min per baris
min2

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 3, 0, 4, 3], dtype=int64)>

###  Hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [40]:
concat1 = random_tensor
concat2 = prime_tensor

In [41]:
concat12 = tf.concat([concat1, concat2], axis = 0)
concat12

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-1.0919173 , -0.50867236, -0.60065955, -1.1253885 , -0.8871544 ],
       [-0.6092709 ,  0.587739  , -0.29714295, -0.8393197 ,  0.9166867 ],
       [-0.10452037,  1.3851545 ,  0.4848608 ,  0.2158733 ,  0.8586742 ],
       [ 0.76974714, -0.31655243, -0.17181592, -0.544253  , -1.0112499 ],
       [-1.3278526 ,  0.12330144,  1.8880543 , -1.6810323 ,  1.5303435 ],
       [ 2.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [13.        , 17.        , 19.        , 23.        , 29.        ],
       [31.        , 37.        , 41.        , 43.        , 47.        ],
       [53.        , 59.        , 61.        , 67.        , 71.        ],
       [73.        , 79.        , 83.        , 89.        , 97.        ]],
      dtype=float32)>

###  Hasil sorting dari kedua variable di atas (descending)

In [42]:
sort1 = random_tensor
sort2= prime_tensor

In [43]:
sort_desc = tf.sort([sort1, sort2], direction="DESCENDING")
sort_desc

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[-0.50867236, -0.60065955, -0.8871544 , -1.0919173 ,
         -1.1253885 ],
        [ 0.9166867 ,  0.587739  , -0.29714295, -0.6092709 ,
         -0.8393197 ],
        [ 1.3851545 ,  0.8586742 ,  0.4848608 ,  0.2158733 ,
         -0.10452037],
        [ 0.76974714, -0.17181592, -0.31655243, -0.544253  ,
         -1.0112499 ],
        [ 1.8880543 ,  1.5303435 ,  0.12330144, -1.3278526 ,
         -1.6810323 ]],

       [[11.        ,  7.        ,  5.        ,  3.        ,
          2.        ],
        [29.        , 23.        , 19.        , 17.        ,
         13.        ],
        [47.        , 43.        , 41.        , 37.        ,
         31.        ],
        [71.        , 67.        , 61.        , 59.        ,
         53.        ],
        [97.        , 89.        , 83.        , 79.        ,
         73.        ]]], dtype=float32)>